"""
NIE Training Data
=================
Training examples for the Neural Intent Engine.

Categories:
  0 = LOCK_SYSTEM       - Lock/secure the computer
  1 = VOLUME_UP         - Increase volume
  2 = VOLUME_DOWN       - Decrease volume
  3 = SYSTEM_STATUS     - Check CPU, RAM, battery, disk
  4 = OPEN_APP          - Launch/open an application
  5 = CLOSE_APP         - Close/kill an application
  6 = SCREENSHOT        - Take a screenshot
  7 = BRIGHTNESS_UP     - Increase screen brightness
  8 = BRIGHTNESS_DOWN   - Decrease screen brightness
  9 = UNKNOWN           - Anything else (falls to LLM)
"""

# Intent label mappings
INTENT_LABELS = {
    0: "LOCK_SYSTEM",
    1: "VOLUME_UP",
    2: "VOLUME_DOWN",
    3: "SYSTEM_STATUS",
    4: "OPEN_APP",
    5: "CLOSE_APP",
    6: "SCREENSHOT",
    7: "BRIGHTNESS_UP",
    8: "BRIGHTNESS_DOWN",
    9: "SHUTDOWN",
    10: "RESTART",
    11: "UNKNOWN",
}

LABEL_TO_ID = {v: k for k, v in INTENT_LABELS.items()}
NUM_INTENTS = len(INTENT_LABELS)

# ──────────────────────────────────────────────────
# Training data: (sentence, category_id)
# ──────────────────────────────────────────────────
TRAINING_DATA = [
    # ── Category 0: LOCK_SYSTEM ──
    ("lock my computer", 0),
    ("secure the laptop", 0),
    ("lock this pc", 0),
    ("lock the screen", 0),
    ("please lock my machine", 0),
    ("put the computer to lock", 0),
    ("activate screen lock", 0),
    ("enable lock screen", 0),
    ("lock the workstation", 0),
    ("secure my pc", 0),
    ("lock screen now", 0),
    ("i want to lock this computer", 0),
    ("can you lock my system", 0),
    ("put my pc on lock", 0),
    ("turn on screen lock", 0),
    ("engage the lock", 0),
    ("lock it", 0),
    ("lock the system", 0),
    ("secure this machine", 0),
    ("please secure the computer", 0),
    ("protect my computer", 0),
    ("activate the lock now", 0),
    ("lock down the computer", 0),
    ("lock my device", 0),
    ("quick lock", 0),

    # ── Category 1: VOLUME_UP ──
    ("increase volume", 1),
    ("turn up the volume", 1),
    ("make it louder", 1),
    ("raise the volume", 1),
    ("volume up", 1),
    ("crank up the volume", 1),
    ("boost the sound", 1),
    ("pump up the volume", 1),
    ("i need more volume", 1),
    ("turn the speakers up", 1),
    ("turn the volume up", 1),
    ("increase the audio", 1),
    ("louder please", 1),
    ("make the sound louder", 1),
    ("more volume please", 1),
    ("amplify the sound", 1),
    ("speakers louder", 1),
    ("raise audio level", 1),
    ("higher volume", 1),
    ("volume needs to go up", 1),
    ("maximize the volume", 1),
    ("increase speaker volume", 1),
    ("turn it up", 1),
    ("sound up", 1),
    ("bump up the volume", 1),
    ("set volume to 50", 1),
    ("set volume 80", 1),
    ("volume 75", 1),
    ("set the volume to 30", 1),
    ("put volume at 60", 1),
    ("change volume to 40", 1),
    ("volume increase 50", 1),
    ("increase volume 25", 1),
    ("increase volume to 90", 1),
    ("make volume 100", 1),
    ("volume to 50 percent", 1),
    ("set sound to 70", 1),

    # ── Category 2: VOLUME_DOWN ──
    ("decrease volume", 2),
    ("turn down the volume", 2),
    ("lower the volume", 2),
    ("make it quieter", 2),
    ("volume down", 2),
    ("reduce the volume", 2),
    ("soften the sound", 2),
    ("too loud turn it down", 2),
    ("bring the volume down", 2),
    ("turn the volume down", 2),
    ("decrease the audio", 2),
    ("quieter please", 2),
    ("make the sound quieter", 2),
    ("less volume please", 2),
    ("reduce audio level", 2),
    ("speakers quieter", 2),
    ("turn it down", 2),
    ("lower volume", 2),
    ("volume needs to go down", 2),
    ("minimize the volume", 2),
    ("reduce speaker volume", 2),
    ("sound down", 2),
    ("mute a little", 2),
    ("lower the audio", 2),
    ("dial down the volume", 2),
    ("decrease volume to 20", 2),
    ("lower volume to 10", 2),
    ("reduce volume 15", 2),
    ("volume down to 5", 2),
    ("bring volume to 0", 2),
    ("turn volume down to 30", 2),

    # ── Category 3: SYSTEM_STATUS ──
    ("check system status", 3),
    ("how is the system", 3),
    ("cpu usage", 3),
    ("check cpu", 3),
    ("battery status", 3),
    ("what is my battery percentage", 3),
    ("how much battery is left", 3),
    ("show me the battery level", 3),
    ("what is cpu utilization", 3),
    ("how is the system doing", 3),
    ("show system info", 3),
    ("check memory usage", 3),
    ("ram status", 3),
    ("disk space", 3),
    ("what is the cpu load", 3),
    ("battery percentage", 3),
    ("system health check", 3),
    ("how much ram is being used", 3),
    ("check system performance", 3),
    ("show me system stats", 3),
    ("computer status", 3),
    ("device health", 3),
    ("is my battery low", 3),
    ("check battery level", 3),
    ("tell me the system status", 3),
    ("how much storage is left", 3),
    ("show disk usage", 3),
    ("performance report", 3),
    ("give me a status update", 3),
    ("hardware status", 3),
    ("system diagnostics", 3),
    ("monitor cpu", 3),
    ("resource usage", 3),
    ("whats my battery", 3),

    # ── Category 4: OPEN_APP ──
    ("open chrome", 4),
    ("launch chrome", 4),
    ("start chrome", 4),
    ("open google chrome", 4),
    ("open notepad", 4),
    ("launch notepad", 4),
    ("start notepad", 4),
    ("open calculator", 4),
    ("launch calculator", 4),
    ("open file explorer", 4),
    ("launch file explorer", 4),
    ("open explorer", 4),
    ("open task manager", 4),
    ("launch task manager", 4),
    ("open settings", 4),
    ("launch settings", 4),
    ("open the browser", 4),
    ("start the browser", 4),
    ("open brave", 4),
    ("launch brave", 4),
    ("open firefox", 4),
    ("launch firefox", 4),
    ("open edge", 4),
    ("launch edge", 4),
    ("open vscode", 4),
    ("launch vscode", 4),
    ("open vs code", 4),
    ("start vs code", 4),
    ("open word", 4),
    ("launch word", 4),
    ("open excel", 4),
    ("launch excel", 4),
    ("open paint", 4),
    ("open terminal", 4),
    ("launch terminal", 4),
    ("open command prompt", 4),
    ("launch cmd", 4),
    ("open powershell", 4),
    ("start an application", 4),
    ("run chrome", 4),
    ("run notepad", 4),
    ("can you open chrome", 4),
    ("please open notepad", 4),
    ("i want to open calculator", 4),
    ("fire up chrome", 4),
    ("open spotify", 4),
    ("launch spotify", 4),

    # ── Category 5: CLOSE_APP ──
    ("close chrome", 5),
    ("kill chrome", 5),
    ("stop chrome", 5),
    ("close notepad", 5),
    ("kill notepad", 5),
    ("close the browser", 5),
    ("close task manager", 5),
    ("kill task manager", 5),
    ("close all chrome windows", 5),
    ("end chrome process", 5),
    ("terminate chrome", 5),
    ("shut down chrome", 5),
    ("close firefox", 5),
    ("kill firefox", 5),
    ("close edge", 5),
    ("close vscode", 5),
    ("kill vscode", 5),
    ("close that application", 5),
    ("close the app", 5),
    ("force close chrome", 5),
    ("end task chrome", 5),
    ("close excel", 5),
    ("kill the process", 5),
    ("terminate the program", 5),
    ("close spotify", 5),

    # ── Category 6: SCREENSHOT ──
    ("take a screenshot", 6),
    ("capture the screen", 6),
    ("screenshot please", 6),
    ("take a screen capture", 6),
    ("grab the screen", 6),
    ("save a screenshot", 6),
    ("capture my screen", 6),
    ("take screen snapshot", 6),
    ("snap the screen", 6),
    ("screenshot now", 6),
    ("screen capture", 6),
    ("print screen", 6),
    ("snapshot the screen", 6),
    ("capture this screen", 6),
    ("take a picture of my screen", 6),
    ("screenshot my desktop", 6),
    ("grab a screenshot", 6),
    ("save my screen", 6),
    ("capture what i see", 6),
    ("take a snap of the screen", 6),

    # ── Category 7: BRIGHTNESS_UP ──
    ("increase brightness", 7),
    ("make the screen brighter", 7),
    ("turn up the brightness", 7),
    ("brightness up", 7),
    ("raise the brightness", 7),
    ("brighter please", 7),
    ("increase screen brightness", 7),
    ("make it brighter", 7),
    ("boost brightness", 7),
    ("more brightness", 7),
    ("turn up display brightness", 7),
    ("screen brighter", 7),
    ("higher brightness", 7),
    ("brighten the screen", 7),
    ("brighten the display", 7),
    ("i need more brightness", 7),
    ("the screen is too dark", 7),
    ("too dark increase brightness", 7),
    ("display brighter", 7),
    ("light up the screen", 7),
    ("set brightness to 80", 7),
    ("set brightness 60", 7),
    ("brightness 75", 7),
    ("set the brightness to 50", 7),
    ("put brightness at 90", 7),
    ("change brightness to 100", 7),
    ("increase brightness to 70", 7),
    ("brightness to 80 percent", 7),
    ("set screen brightness 50", 7),

    # ── Category 8: BRIGHTNESS_DOWN ──
    ("decrease brightness", 8),
    ("make the screen dimmer", 8),
    ("turn down the brightness", 8),
    ("brightness down", 8),
    ("lower the brightness", 8),
    ("dimmer please", 8),
    ("decrease screen brightness", 8),
    ("make it dimmer", 8),
    ("reduce brightness", 8),
    ("less brightness", 8),
    ("turn down display brightness", 8),
    ("screen dimmer", 8),
    ("lower brightness", 8),
    ("dim the screen", 8),
    ("dim the display", 8),
    ("i need less brightness", 8),
    ("the screen is too bright", 8),
    ("too bright decrease brightness", 8),
    ("display dimmer", 8),
    ("darken the screen", 8),
    ("decrease brightness to 20", 8),
    ("lower brightness to 10", 8),
    ("reduce brightness 30", 8),
    ("brightness down to 15", 8),
    ("dim to 5 percent", 8),
    ("set brightness to 25", 8),

    # ── Category 9: SHUTDOWN ──
    ("shutdown the computer", 9),
    ("power off", 9),
    ("turn off my pc", 9),
    ("shut down system", 9),
    ("turn off the computer", 9),
    ("power down", 9),
    ("shutdown now", 9),
    ("turn off laptop", 9),
    ("kill power", 9),
    ("shutdown my laptop", 9),
    ("initiate shutdown", 9),
    ("goodbye nova shutdown", 9),

    # ── Category 10: RESTART ──
    ("restart the computer", 10),
    ("reboot system", 10),
    ("restart pc", 10),
    ("reboot now", 10),
    ("restart laptop", 10),
    ("cycle power", 10),
    ("reset the system", 10),
    ("reboot machine", 10),
    ("restart my computer", 10),
    ("restart nova and pc", 10),

    # ── Category 11: UNKNOWN (conversational / misc) ──
    ("tell me a joke", 11),
    ("what is the weather", 11),
    ("hello there", 11),
    ("how are you doing", 11),
    ("what is your name", 11),
    ("who created you", 11),
    ("play some music", 11),
    ("search for cats on the internet", 11),
    ("write me a poem", 11),
    ("what is the capital of france", 11),
    ("translate hello to spanish", 11),
    ("set an alarm for seven am", 11),
    ("remind me to buy milk", 11),
    ("calculate three plus four", 11),
    ("what time is it", 11),
    ("good morning", 11),
    ("thank you very much", 11),
    ("send an email to john", 11),
    ("book a flight to new york", 11),
    ("navigate to the nearest restaurant", 11),
    ("read the news", 11),
    ("give me a recipe for pasta", 11),
    ("help me with my homework", 11),
    ("what day is today", 11),
    ("describe the meaning of life", 11),
    ("do you like pizza", 11),
    ("tell me about yourself", 11),
    ("show me random facts", 11),
    ("can you sing a song", 11),
    ("what is the weather today", 11),
    ("how is the weather outside", 11),
    ("whats the temperature", 11),
    ("is it raining", 11),
    ("create a new file", 11),
    ("delete this folder", 11),
    ("make me a sandwich", 11),
    ("what is the meaning of nova", 11),
    ("when was python invented", 11),
    ("how tall is mount everest", 11),
    ("show me the news headlines", 11),
    ("what are the latest movies", 11),
    ("order some food", 11),
    ("take me home", 11),
    ("find my phone", 11),
    ("where is the nearest atm", 11),
    ("turn on the lights", 11),
    ("switch off the fan", 11),
    ("hi", 11),
    ("hey", 11),
    ("hey there", 11),
    ("yo", 11),
    ("hi nova", 11),
    ("hello", 11),
    ("bye", 11),
    ("goodbye", 11),
    ("see you later", 11),
    ("thanks", 11),
    ("ok", 11),
    ("sure", 11),
    ("nice", 11),
    ("cool", 11),
    ("what can you do", 11),
    ("help me", 11),
    ("who are you", 11),
    ("what are you", 11),
    ("how old are you", 11),
    ("whats up", 11),
    ("good evening", 11),
    ("good night", 11),
]

# Validation set (unseen examples to test generalization)
VALIDATION_DATA = [
    ("lock this machine right now", 0),
    ("secure my workstation", 0),
    ("please activate lock", 0),
    ("engage screen lock immediately", 0),
    ("keep my pc safe lock it", 0),

    ("make the speakers louder", 1),
    ("i need more volume", 1),
    ("please increase the volume", 1),
    ("the audio is too low turn it up", 1),
    ("amplify please", 1),

    ("turn the speakers down", 2),
    ("i need less volume", 2),
    ("please decrease the volume", 2),
    ("the audio is too high turn it down", 2),
    ("reduce the noise", 2),

    ("what is memory consumption", 3),
    ("give me a battery update", 3),
    ("how is cpu performing", 3),
    ("show me storage information", 3),
    ("current system load", 3),

    ("open google chrome for me", 4),
    ("can you launch the calculator", 4),
    ("start up vscode please", 4),
    ("fire up the browser", 4),
    ("run file explorer", 4),

    ("shut down chrome please", 5),
    ("kill the notepad process", 5),
    ("close that program", 5),
    ("end the firefox process", 5),
    ("terminate edge browser", 5),

    ("save this screen to my desktop", 6),
    ("image of my screen please", 6),
    ("grab screenshot now", 6),
    ("take picture of monitor", 6),
    ("screen grab", 6),

    ("make the brightness higher", 7),
    ("increase the light", 7),
    ("brighter screen please", 7),
    ("boost the backlight", 7),
    ("turn up the light", 7),

    ("make the brightness lower", 8),
    ("decrease the light", 8),
    ("dimmer screen please", 8),
    ("lower the backlight", 8),
    ("turn down the light", 8),

    ("turn off this machine", 9),
    ("shutdown system immediately", 9),
    ("kill the power supply", 9),
    ("halt the system", 9),
    ("power down the laptop", 9),

    ("restart everything", 10),
    ("reboot the workstation", 10),
    ("soft reset", 10),
    ("cycle the power", 10),
    ("restart my windows", 10),

    ("i am feeling happy", 11),
    ("do you dream", 11),
    ("what is quantum physics", 11),
    ("sing me a lullaby", 11),
    ("who is the president", 11),
]
